node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('Install dependencies') {
     nodejs(nodeJSInstallationName: 'Node JS LTS') {
       sh 'npm install'
     }
   }
   stage('unit tests') {
     nodejs(nodeJSInstallationName: 'Node JS LTS') {
      sh "npm test"
     }
   }

  //  stage('protractor tests') {
  //    stage('unit tests') {
  //    nodejs(nodeJSInstallationName: 'Node JS LTS') {
  //     sh "npm run e2e"
  //    }
  //   }
  //  }
   stage('heroku-create-staging') {
     sh 'echo Creating dlsu-obqa-web-ui-staging'
     sh 'heroku create dlsu-obqa-web-ui-staging'
     sh 'git checkout master'
     sh 'git push heroku master'
     sh 'heroku ps:scale web=1'     
   }
}
