export const SESSION_CREATE_ATTEMPT: string = 'SESSION_CREATE_ATTEMPT';
export const SESSION_CREATE_FULFILLED: string = 'SESSION_CREATE_FULFILLED';
export const SESSION_CREATE_FAILED: string = 'SESSION_CREATE_FAILED';
export const SESSION_DESTROY_FULFILLED: string = 'SESSION_DESTROY_FULFILLED';
export const SESSION_CHECK_ATTEMPT: string = 'SESSION_CHECK_ATTEMPT';
export const SESSION_CHECK_FULFILLED: string = 'SESSION_CHECK_FULFILLED';
export const SESSION_CHECK_FAILED: string = 'SESSION_CHECK_FAILED';