export const USER_CREATE_ATTEMPT: string = 'USER_CREATE_ATTEMPT';
export const USER_CREATE_FULFILLED: string = 'USER_CREATE_FULFILLED';
export const USER_CREATE_FAILED: string = 'USER_CREATE_FAILED';
export const TOGGLE_USER_CREATE: string = 'TOGGLE_USER_CREATE';